module.exports = {
  projects: [
    {
      title: "Punctually",
      subtitle: "a schedule generator app demo",
      image: "/assets/projects/punctually.jpg",
      technologies: ["NextJS", "Sass"],
      url: "https://punctually.vercel.app",
    },
    {
      title: "Twitterclone",
      subtitle: "a semi-functioning clone of Twitter",
      image: "/assets/projects/twitter.jpg",
      technologies: [
        "React",
        "Sass",
        "Framer Motion",
        "Firebase Cloud Firestore",
      ],
      url: "https://twitterclone.mikepodo.net",
    },
    {
      title: "Portfolio v2",
      subtitle: "v2 of mikepodo.net",
      image: "/assets/projects/portfolio2.jpg",
      technologies: ["React", "Styled-Components", "Framer Motion"],
      url: "https://mikepodo.netlify.app",
    },
    {
      title: "Ignite",
      subtitle: "a site utilizing an API to display categorized video games",
      image: "/assets/projects/ignite.jpg",
      technologies: [
        "React",
        "React-Router",
        "Styled-Components",
        "Framer Motion",
        "Redux",
        "Axios",
      ],
      url: "https://mikepodo-ignite.netlify.app/",
    },
    {
      title: "Capture",
      subtitle: "a template website for any general business",
      image: "/assets/projects/capture.jpg",
      technologies: [
        "React",
        "React-Router",
        "Styled-Components",
        "Framer Motion",
      ],
      url: "https://mikepodo-capture.netlify.app/",
    },
    {
      title: "Waves",
      subtitle: "a React media player",
      image: "/assets/projects/waves.jpg",
      technologies: ["React", "Sass"],
      url: "https://mikepodo-waves.netlify.app/",
    },
    {
      title: "Coolors",
      subtitle: "a color-picking toolkit for web developers",
      image: "/assets/projects/coolors.jpg",
      technologies: ["JavaScript", "HTML", "Sass"],
      url: "https://mikepodo-coolors.netlify.app/",
    },
    {
      title: "Beatmaker",
      subtitle: "a musical drum beat site",
      image: "/assets/projects/beatmaker.jpg",
      technologies: ["JavaScript", "HTML", "Sass"],
      url: "https://mikepodo-beatmaker.netlify.app/",
    },
    {
      title: "Todo List",
      subtitle: "a beginner programmer's todo list application",
      image: "/assets/projects/todolist.jpg",
      technologies: ["JavaScript", "HTML", "Sass"],
      url: "https://mikepodo-todolist.netlify.app/",
    },
    {
      title: "Portfolio v1",
      subtitle: "v1 of mikepodo.net",
      image: "/assets/projects/portfolio1.jpg",
      technologies: ["HTML", "Sass"],
      url: "https://mikepodo-portfolio.netlify.app/",
    },
    {
      title: "BMI Calculator",
      subtitle: "a calculator used to find one's body mass index",
      image: "/assets/projects/bmi.jpg",
      technologies: ["JavaScript", "HTML", "Sass"],
      url: "https://mikepodo-bmi-calculator.netlify.app/",
    },
  ],
};
